name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "node"

      - run: npm install
      - run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Gunakan PAT dari secret
          github_token: ${{ secrets.GH_PAGES_TOKEN }}

          # Target repo:
          external_repository: catsitterbanyuwangi/catsitterbanyuwangi.github.io

          # Branch target
          publish_branch: gh-pages

          publish_dir: ./out
          keep_files: false
