name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Penting! Token untuk checkout
          token: ${{ secrets.GH_DEPLOY_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "node"

      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_DEPLOY_TOKEN }}
          external_repository: catsitterbanyuwangi/catsitterbanyuwangi.github.io
          publish_branch: gh-pages
          publish_dir: ./out
          keep_files: false
          force_orphan: true
